# change it: host, db, user, password

STATIC_ROOT: '/static/'

ALLOWED_HOSTS:
  - host

DATABASES:
  default:
    ENGINE: django.db.backends.postgresql_psycopg2
    NAME: db
    USER: user
    PASSWORD: password
    HOST: postgres
    PORT: ''
